#!/bin/bash

set -ex

pip install --upgrade git+https://github.com/zillow/metaflow.git@tz/coverage
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
poetry config experimental.new-installer false
poetry install -E dask

#jupyter lab workspaces import binder/tutorials.jupyterlab-workspace || true