#!/bin/bash

set -ex

pip install --upgrade git+https://github.com/zillow/metaflow.git@tz/coverage
pip install pandas dask pandas pyspark
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

which python
$HOME/.poetry/bin/poetry run which python

$HOME/.poetry/bin/poetry config experimental.new-installer false
$HOME/.poetry/bin/poetry install -E dask -E spark